<?php

return [
    [
        "customer_name" => "Paolo",
        "customer_surname" => "Duzioni",
        "customer_address" => "Viale Ungheria",
        "customer_email" => "paolo@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 12.50,
        "user_id" => 1,
    ],
    [
        "customer_name" => "Antonio",
        "customer_surname" => "Rossi",
        "customer_address" => "Viale Rossi",
        "customer_email" => "antonio@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 19.50,
        "user_id" => 1,
    ],
    [
        "customer_name" => "Fabrizio",
        "customer_surname" => "Biachi",
        "customer_address" => "Viale Bianchi",
        "customer_email" => "fabri@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 21.50,
        "user_id" => 1,
    ],
    [
        "customer_name" => "Galileo",
        "customer_surname" => "Galilei",
        "customer_address" => "Viale Galileo",
        "customer_email" => "gali@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 32.50,
        "user_id" => 2,
    ],
    [
        "customer_name" => "Luigi",
        "customer_surname" => "Scarponi",
        "customer_address" => "Viale scarpe",
        "customer_email" => "luigi@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 9.90,
        "user_id" => 2,
    ],
    [
        "customer_name" => "Mirko",
        "customer_surname" => "Marchi",
        "customer_address" => "Viale Marzo",
        "customer_email" => "mirko@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 10.00,
        "user_id" => 2,
    ],
    [
        "customer_name" => "Antonella",
        "customer_surname" => "Clerici",
        "customer_address" => "Viale Rai",
        "customer_email" => "antonella@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 41.70,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Barbara",
        "customer_surname" => "Durso",
        "customer_address" => "Viale Dementi",
        "customer_email" => "barb@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 54.49,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Michael",
        "customer_surname" => "Jordan",
        "customer_address" => "Viale Palla",
        "customer_email" => "mm@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 78.50,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Francesco",
        "customer_surname" => "Totti",
        "customer_address" => "Viale Roma",
        "customer_email" => "pupone@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 21.50,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Antonio",
        "customer_surname" => "Montenovo",
        "customer_address" => "Viale Europa",
        "customer_email" => "antonionio@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 30.50,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Luigi",
        "customer_surname" => "Rosso",
        "customer_address" => "Viale Svizzera",
        "customer_email" => "luigirosso@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 65.50,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Antonello",
        "customer_surname" => "Venditti",
        "customer_address" => "Viale Roma",
        "customer_email" => "antoroma@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 78.50,
        "user_id" => 3,
    ],
    [
        "customer_name" => "Claudio",
        "customer_surname" => "Baglioni",
        "customer_address" => "Viale Tuscolana",
        "customer_email" => "claba@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 68.50,
        "user_id" => 4,
    ],
    [
        "customer_name" => "Paolo",
        "customer_surname" => "Maldini",
        "customer_address" => "Via Milano",
        "customer_email" => "mediolanum@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 25.50,
        "user_id" => 4,
    ],
    [
        "customer_name" => "Alessandro",
        "customer_surname" => "Costacurta",
        "customer_address" => "Via Internazionale",
        "customer_email" => "alecosta@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 88.50,
        "user_id" => 5,
    ],
    [
        "customer_name" => "Cristiano",
        "customer_surname" => "Ronaldo",
        "customer_address" => "Via da Torino",
        "customer_email" => "cr7@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 140.50,
        "user_id" => 5,
    ],
    [
        "customer_name" => "Gigi",
        "customer_surname" => "Proietti",
        "customer_address" => "Via Tufello",
        "customer_email" => "gigipro@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 90.00,
        "user_id" => 5,
    ],
    [
        "customer_name" => "Moreno",
        "customer_surname" => "Torricelli",
        "customer_address" => "Via Florentia",
        "customer_email" => "moretorri@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 35.00,
        "user_id" => 5,
    ],
    [
        "customer_name" => "David",
        "customer_surname" => "Trezeguet",
        "customer_address" => "Via Francia",
        "customer_email" => "davidtrezeguet@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 55.00,
        "user_id" => 5,
    ],
    [
        "customer_name" => "Paolo",
        "customer_surname" => "Duzioni",
        "customer_address" => "Viale Ungheria",
        "customer_email" => "paolo@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 12.50,
        "user_id" => 6,
    ],
    [
        "customer_name" => "Antonio",
        "customer_surname" => "Rossi",
        "customer_address" => "Viale Rossi",
        "customer_email" => "antonio@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 19.50,
        "user_id" => 6,
    ],
    [
        "customer_name" => "Fabrizio",
        "customer_surname" => "Biachi",
        "customer_address" => "Viale Bianchi",
        "customer_email" => "fabri@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 21.50,
        "user_id" => 6,
    ],
    [
        "customer_name" => "Galileo",
        "customer_surname" => "Galilei",
        "customer_address" => "Viale Galileo",
        "customer_email" => "gali@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 32.50,
        "user_id" => 7,
    ],
    [
        "customer_name" => "Luigi",
        "customer_surname" => "Scarponi",
        "customer_address" => "Viale scarpe",
        "customer_email" => "luigi@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 9.90,
        "user_id" => 7,
    ],
    [
        "customer_name" => "Mirko",
        "customer_surname" => "Marchi",
        "customer_address" => "Viale Marzo",
        "customer_email" => "mirko@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 10.00,
        "user_id" => 7,
    ],
    [
        "customer_name" => "Antonella",
        "customer_surname" => "Clerici",
        "customer_address" => "Viale Rai",
        "customer_email" => "antonella@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 41.70,
        "user_id" => 8,
    ],
    [
        "customer_name" => "Barbara",
        "customer_surname" => "Durso",
        "customer_address" => "Viale Dementi",
        "customer_email" => "barb@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 54.49,
        "user_id" => 8,
    ],
    [
        "customer_name" => "Michael",
        "customer_surname" => "Jordan",
        "customer_address" => "Viale Palla",
        "customer_email" => "mm@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 78.50,
        "user_id" => 8,
    ],
    [
        "customer_name" => "Francesco",
        "customer_surname" => "Totti",
        "customer_address" => "Viale Roma",
        "customer_email" => "pupone@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 21.50,
        "user_id" => 8,
    ],
    [
        "customer_name" => "Antonio",
        "customer_surname" => "Montenovo",
        "customer_address" => "Viale Europa",
        "customer_email" => "antonionio@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 30.50,
        "user_id" => 9,
    ],
    [
        "customer_name" => "Luigi",
        "customer_surname" => "Rosso",
        "customer_address" => "Viale Svizzera",
        "customer_email" => "luigirosso@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 65.50,
        "user_id" => 9,
    ],
    [
        "customer_name" => "Antonello",
        "customer_surname" => "Venditti",
        "customer_address" => "Viale Roma",
        "customer_email" => "antoroma@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 78.50,
        "user_id" => 9,
    ],
    [
        "customer_name" => "Claudio",
        "customer_surname" => "Baglioni",
        "customer_address" => "Viale Tuscolana",
        "customer_email" => "claba@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 68.50,
        "user_id" => 10,
    ],
    [
        "customer_name" => "Paolo",
        "customer_surname" => "Maldini",
        "customer_address" => "Via Milano",
        "customer_email" => "mediolanum@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 25.50,
        "user_id" => 10,
    ],
    [
        "customer_name" => "Alessandro",
        "customer_surname" => "Costacurta",
        "customer_address" => "Via Internazionale",
        "customer_email" => "alecosta@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 88.50,
        "user_id" => 10,
    ],
    [
        "customer_name" => "Cristiano",
        "customer_surname" => "Ronaldo",
        "customer_address" => "Via da Torino",
        "customer_email" => "cr7@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 140.50,
        "user_id" => 11,
    ],
    [
        "customer_name" => "Gigi",
        "customer_surname" => "Proietti",
        "customer_address" => "Via Tufello",
        "customer_email" => "gigipro@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 90.00,
        "user_id" => 11,
    ],
    [
        "customer_name" => "Moreno",
        "customer_surname" => "Torricelli",
        "customer_address" => "Via Florentia",
        "customer_email" => "moretorri@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 35.00,
        "user_id" => 12,
    ],
    [
        "customer_name" => "David",
        "customer_surname" => "Trezeguet",
        "customer_address" => "Via Francia",
        "customer_email" => "davidtrezeguet@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 55.00,
        "user_id" => 12,
    ],
    [
        "customer_name" => "Francesco",
        "customer_surname" => "Totti",
        "customer_address" => "Viale Roma",
        "customer_email" => "pupone@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 21.50,
        "user_id" => 13,
    ],
    [
        "customer_name" => "Antonio",
        "customer_surname" => "Montenovo",
        "customer_address" => "Viale Europa",
        "customer_email" => "antonionio@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 30.50,
        "user_id" => 13,
    ],
    [
        "customer_name" => "Luigi",
        "customer_surname" => "Rosso",
        "customer_address" => "Viale Svizzera",
        "customer_email" => "luigirosso@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 65.50,
        "user_id" => 13,
    ],
    [
        "customer_name" => "Antonello",
        "customer_surname" => "Venditti",
        "customer_address" => "Viale Roma",
        "customer_email" => "antoroma@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 78.50,
        "user_id" => 14,
    ],
    [
        "customer_name" => "Claudio",
        "customer_surname" => "Baglioni",
        "customer_address" => "Viale Tuscolana",
        "customer_email" => "claba@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 68.50,
        "user_id" => 14,
    ],
    [
        "customer_name" => "Paolo",
        "customer_surname" => "Maldini",
        "customer_address" => "Via Milano",
        "customer_email" => "mediolanum@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 25.50,
        "user_id" => 14,
    ],
    [
        "customer_name" => "Alessandro",
        "customer_surname" => "Costacurta",
        "customer_address" => "Via Internazionale",
        "customer_email" => "alecosta@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 88.50,
        "user_id" => 15,
    ],
    [
        "customer_name" => "Cristiano",
        "customer_surname" => "Ronaldo",
        "customer_address" => "Via da Torino",
        "customer_email" => "cr7@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 140.50,
        "user_id" => 15,
    ],
    [
        "customer_name" => "Gigi",
        "customer_surname" => "Proietti",
        "customer_address" => "Via Tufello",
        "customer_email" => "gigipro@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 90.00,
        "user_id" => 16,
    ],
    [
        "customer_name" => "Moreno",
        "customer_surname" => "Torricelli",
        "customer_address" => "Via Florentia",
        "customer_email" => "moretorri@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 35.00,
        "user_id" => 16,
    ],
    [
        "customer_name" => "David",
        "customer_surname" => "Trezeguet",
        "customer_address" => "Via Francia",
        "customer_email" => "davidtrezeguet@test.com",
        "customer_phone" => "3935426159",
        "total_price" => 55.00,
        "user_id" => 16,
    ],

]



?>