<?php

return [
	[
		'name' => 'Margherita',
		'description' => 'La più classica delle pizze, intramontabile',
		'ingredients' => 'pomodoro, mozzarella, basilico',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80',
	], [
		'name' => 'Pizza con Salsiccia',
		'description' => 'La più classica delle pizze, ma con la salsiccia',
		'ingredients' => 'pomodoro, mozzarella, basilico, salsiccia fresca',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80',
	],
	[
		'name' => 'Adamo ed Eva',
		'description' => 'Direttamente dal giardino dell\'Eden',
		'ingredients' => 'mozzarella, basilico, rosmarino, mela',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1593504049359-74330189a345?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'
	],
	[
		'name' => 'Trentina',
		'description' => 'Speck, burrata, radicchio, basilico',
		'ingredients' => 'pomodoro, mozzarella, basilico',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],
	[
		'name' => 'Fourmaggi',
		'description' => 'Four-maggi',
		'ingredients' => 'pomodoro, mozzarella, taleggio, gorgonzola, tomino, pepe, noce moscata',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1620374645498-af6bd681a0bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],
	[
		'name' => 'Cotto di te',
		'description' => 'Una dolce dedica d\ammore al prosciutto cotto',
		'ingredients' => 'mozzarella, olive, carciofini, crema di funghi, basilico e prosciutto cotto di Parma',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1639428132044-d28ab64ca487?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
	],
	[
		'name' => 'Sogno Vegano',
		'description' => '',
		'ingredients' => 'Tacos vegani',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1511690078903-71dc5a49f5e3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
	],
	[
		'name' => 'Cecina',
		'description' => 'Non siamo toscani, ma ci piacciono i ceci',
		'ingredients' => 'Crema di ceci, cavolo nero, pesto di pomodorini, semi di lino',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1602873520153-ec56ca3c205b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	[
		'name' => 'Squaw Steak',
		'description' => 'Entrecote di Manzo di prima scelta alla griglia',
		'ingredients' => 'Manzo, patate fritte, rucola, grana, salsa BBQ',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],
	[
		'name' => 'Cherokee',
		'description' => 'Tagliata di entrecote di manzo alla griglia',
		'ingredients' => 'manzo, rucola, grana a scaglie, patate e salsa BBQ',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1633436375795-12b3b339712f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	[
		'name' => 'Rosemary Fillett',
		'description' => 'Tagliata di di filetto di manzo con polvere di bacon, olio aromatizzato al rosmarino e rucola',
		'ingredients' => 'manzo, rucola, grana a scaglie, patate, rosmarino, paprika e salsa BBQ',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1583953623787-ada99d338235?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80',
	],
	[
		'name' => 'Gran canyon',
		'description' => '330 Gr di carni miste grigliate, accompagnate dai nostri freschi contorni stagionali e da una pioggia di patate fritte',
		'ingredients' => 'manzo, maiale, vitello, peperoni, carciofi, olive, cipolla, patate',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1566149295547-b40efb8e5a81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	[
		'name' => 'London Burger',
		'description' => '',
		'ingredients' => 'Burger di manzo 200gr, salsa BBQ, cipolla, gouda, pomodoro',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=999&q=80',
	],
	[
		'name' => 'Rome Burger',
		'description' => '',
		'ingredients' => 'Burger di manzo 200gr, salsa di carciofi, cipolla, gouda, pomodoro',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1603064752734-4c48eff53d05?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
	],
	[
		'name' => 'Trentin Burger',
		'description' => '',
		'ingredients' => 'Burger di manzo 120gr, speck, scamorza, pomodorini, tomino grigliato',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=722&q=80',
	],
	[
		'name' => 'Socmel',
		'description' => '',
		'ingredients' => 'Focaccia bolognese con ciccioli, squacquerone, ragù bolognese',
		'visibility' => true,
		'thumb' => '',
	],
	[
		'name' => 'American Burger',
		'description' => '',
		'ingredients' => 'Burger di manzo 230gr, salsa BBQ, cipolla fritta, cheddar, pomodoro, insalata, bacon, maionese e ketchup',
		'visibility' => false,
		'thumb' => '',
	],
	[
		'name' => 'Strigoli al pesto',
		'description' => '',
		'ingredients' => 'pasta di semola, basilico, aglio, pesto, olio evo, pinoli, pomodorini',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1445847562439-f251c3799ea5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80',
	],
	[
		'name' => 'fusilli all\'amatriciana',
		'description' => '',
		'ingredients' => 'fusilli, pomodoro, pancetta',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1625333810796-9bf59d01ca10?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=635&q=80',
	],
	[
		'name' => 'Gnocchi alla sorrentina',
		'description' => '',
		'ingredients' => 'gnocchi di patate, pomodoro, basilico, mozzarella filante',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1621340434481-f2a3db584ea6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],
	[
		'name' => 'Tagliatelle pomodoro',
		'description' => '',
		'ingredients' => 'pasta fresca all\'uovo, pomodoro, maiale, manzo, carote, sedano, cipolla',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1522666257812-173fdc2d11fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80',
	],
	[
		'name' => 'Bucatini alla carbonara',
		'description' => '',
		'ingredients' => 'bucatini, guanciale, pepe, uova, pecorino romano',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1627207644206-a2040d60ecad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	//italian 1
	[
		'name' => 'Lasagne',
		'description' => 'Sfoglie a strati condite con sugo di carne, formaggi e salumi',
		'ingredients' => 'mozzarella, pomodoro, carne macinata, sale, pepe, parmigiano',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1619341184948-969a037c0ffa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],[
		'name' => 'Risotto ai funghi',
		'description' => 'Risotto con funghi freschi',
		'ingredients' => 'riso, funghi porcini, sale, pepe',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1637361874063-e5e415d7bcf7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],[
		'name' => 'Polenta',
		'description' => 'Piatto tipico della Pianura Padana',
		'ingredients' => 'farina di mais, sale',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1610964828873-46cc1210a417?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80',
	],[
		'name' => 'Tegamino',
		'description' => 'Pasta cotta in forno in un tegame di terracotta',
		'ingredients' => 'pomodoro, carne tritata, scamorza, salame, sale, pepe',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1598880742072-13b8eef1494d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],[
		'name' => 'Caponata',
		'description' => 'Assortimento diverdure e ortaggi',
		'ingredients' => 'verdure fritte, pomodoro, aceto, salsa agrodolce, sale',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],[
		'name' => 'Spaghetti allo scoglio',
		'description' => 'Spaghetti con crostacei e molluschi',
		'ingredients' => 'pesce misto, pomodoro, sale, pepe',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
	],[
		'name' => 'Cotoletta alla milanese',
		'description' => 'Cotoletta tipica milanese',
		'ingredients' => 'pollo, uova, farina, sale',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Polpette al pomodoro',
		'description' => 'Polpette di macinato condite con pomodoro',
		'ingredients' => 'carne, pomodoro, uova, pane, sale, pepe',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1515516969-d4008cc6241a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],[
		'name' => 'roast beef',
		'thumb' => '',
		'description' => 'Carne di bovino adulto',
		'ingredients' => 'carne manzo, erbe aromatiche, olio Evo, sale, pepe',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Tiramisù',
		'description' => 'Dolce con mascarpone e caffe',
		'ingredients' => 'mascarpone, uova, zucchero, savoiardi, caffè, cacao',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1542124948-dc391252a940?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	//italian 2
	[
		'name' => 'Pasta al pomodoro',
		'description' => 'Pasta condita con pomodori freschi',
		'ingredients' => 'pomodoro, pasta fatta in casa, sale, olio Evo, basilico, parmigiano',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Pasta e rape',
		'description' => 'Piatto tipico meridionale con cime di rapa fresche',
		'ingredients' => 'rape, pasta fatta in casa, peperoni cruschui, mollica fritta, olio Evo',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Gnocchi alla sorrentina',
		'description' => 'Gnocchi con pomodoro e mozzarella filante',
		'ingredients' => 'pomodoro, mozzarella, parmigiano, olio Evo, basilico',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Risotto alla milanese',
		'description' => 'Risotto tipico milanese',
		'ingredients' => 'riso, zafferano, burro, grana padano, sale',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1148&q=80',
	],[
		'name' => 'Pasta con le patate',
		'description' => 'Pasta con patate di prima scelta',
		'ingredients' => 'patate, sale, parmigiano, rosmarino, pomodoro',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Pasta col salmone',
		'description' => 'Pasta con salmone fresco',
		'ingredients' => 'salmone fresco, panna, olio Evo, sale, pepe',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],[
		'name' => 'Tagliata di Angus',
		'description' => 'Tagliata con carne di Angus argentino di prima scelta ',
		'ingredients' => 'carne di manzo, grana padano, rucola, sale, glassa di aceto balsamico',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Polpo alla Luciana',
		'description' => 'Polpo e patate immersi nel sugo di pomodori freschi',
		'ingredients' => 'polpo, patate, pomodoro, sale, olio Evo, peperoncino',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Bignè',
		'description' => 'Dolci alla crema ricoperti con glassatura',
		'ingredients' => 'crema pasticciera, uova, farina, zucchero, burro',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Cannoli siciliani',
		'description' => 'Dolce tipico siciliano con ricotta di pecora',
		'ingredients' => 'ricotta di pecora, zucchero, uova, farina, canditi',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1600975814842-69bd3df9c798?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],
	//italian 3
	[
		'name' => 'Pasta con parmigiano',
		'description' => 'Pasta con Parmigiano di prima qualità',
		'ingredients' => 'parmigiano, olio Evo, sale,',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],[
		'name' => 'Risotto agli asparagi',
		'description' => 'Risotto con asparagi freschi',
		'ingredients' => 'asparagi, riso, parmigianoi, olio Evo, sale, pepe',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Misto di verdure',
		'description' => 'Piatto composto da verdure e ortaggi di stagione',
		'ingredients' => 'melanzane, zucchine, peperoni, cavolfiore, broccoli, pomodoro',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1606791422814-b32c705e3e2f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
	],[
		'name' => 'Pancotto',
		'description' => 'Piatto contadino tipico del meridione',
		'ingredients' => 'pane, rape, uova in camicia, olio Evo, sale, pepe',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Crespelle',
		'description' => 'Un piatto che si scioglie in bocca',
		'ingredients' => 'uova, farina, burro, latte, panna, fughi, sale',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Omelette',
		'description' => 'Frittata di uova sbattute',
		'ingredients' => 'uova, sale, olio Evo, pepe, parmigiano',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1494597706938-de2cd7341979?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1204&q=80',
	],[
		'name' => 'Merluzzo',
		'description' => 'Merluzzo fresco di giornata',
		'ingredients' => 'merluzzo, pomodoro, olive, capperi, olio Evo, origano',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1622119735670-580fb4eb6092?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80',
	],[
		'name' => 'Trippa alla milanese',
		'description' => 'Trippa tipica di Milano',
		'ingredients' => 'trippa, cipolla, lardo, sedano, aglio, carote, parmigiano',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Profitterol',
		'description' => 'Dolce con bignè ripieni di panna e ricoperti di cioccolato',
		'ingredients' => 'uova, farina, zucchero, cacao amaro, panna, strega, latte, burro, cioccolato fondente',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1606163050754-05a6a7530815?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=627&q=80',
	],[
		'name' => 'Panna cotta',
		'description' => 'Dolce semplice e leggero',
		'ingredients' => 'Panna, zucchero, latte, colla di pesce, caramello',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
	],
	//chinese 1
	[
		'name' => 'Riso alla cantonese',
		'description' => 'Riso fritto cinese al salto',
		'ingredients' => 'riso, piselli, prosciutto cotto, erba cipollina, uova',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Involtini primavera',
		'description' => 'Involtini di verdure',
		'ingredients' => 'carote, cavolfiore, cipolle, sale',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Pollo alle mandorle',
		'description' => 'Pollo ricoperto di mandorle',
		'ingredients' => 'pollo, mandorle, salsa di soia, fecola di patate, olio di arachidi, sale',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1525755662778-989d0524087e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
	],[
		'name' => 'Spaghetti di riso ai frutti di mare',
		'description' => 'Spaghetti cinesi conditi con frutti di mare',
		'ingredients' => 'farina di riso, frutti di mare, salsa di soia, verdure',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=992&q=80',
	],[
		'name' => 'Anatra alla pechinese',
		'description' => 'Anatra cucinata nel brodo',
		'ingredients' => 'anatra, brodo, cipolla, zucchero, spezie, zenzero',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Nuvole di drago',
		'description' => 'Gamberetti fritti',
		'ingredients' => 'gamberetti, farina di tapioca, sale, olio di arachidi',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Baozi',
		'description' => 'Tipico panino cotto al vapore ripieno di carne',
		'ingredients' => 'carne di maiale, cipollotto, cavolo, zenzero, salsa di soia, zucchero, sale, pepe',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Pollo al miele',
		'description' => 'Pollo con note dolci di miele',
		'ingredients' => 'pollo, salsa agrodolce, miele, cipollotto, semi di sesamo, salsa di soia',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1013&q=80',
	],[
		'name' => 'Tang yuan',
		'description' => 'Palline di riso glutinoso',
		'ingredients' => 'zenzero, fagioli rossi, sesamo, scorza di mandarino, riso',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Lou po bing',
		'description' => 'Dolce tipico cinese della cucina cantonese',
		'ingredients' => 'sesamo, melone, zucchero, farina di riso, cocco',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1630859311469-289b6a574bdc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
	],
	//chinese 2
	[
		'name' => 'Germogli di bambù con funghi cinesi',
		'description' => 'Germogli di bambù conditi con funghi freschi cinesi',
		'ingredients' => 'funghi, germogli di bambù, zenzero, salsa di soia, sale, zucchero',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => "Costine di maiale all'arancia",
		'description' => 'Costine di maiale preparate con arancia e vino di riso',
		'ingredients' => 'costine di maiale, arancia, zucchero, vino di riso cinese',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Maiale in agrodolce',
		'description' => 'Maiale con note agrodolci',
		'ingredients' => 'maiale, salsa agrodolce, salsa di soia, cipollotto',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1623689046286-01d812cc8bad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1175&q=80',
	],[
		'name' => 'Tagliata di pollo con riso e mandorle ',
		'description' => 'Pollo accompagnato da riso bianco e mandorle in pezzi',
		'ingredients' => 'pollo, limone, mandorle, salsa di soia',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Toast di gamberi',
		'description' => 'Pane ripieno di gamberi e ricoperto di semi di sesamo',
		'ingredients' => 'pane, sesamo, salsa di soia, gamberi, cipolle, amido di mais',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Nian gao',
		'description' => 'Dolce simbolo del capodanno cinese',
		'ingredients' => 'zucchero, riso glutinoso, amido',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Dragon candy',
		'description' => 'Caramelle filanti con semi di sesamo e noccioline',
		'ingredients' => 'zucchero, noccioline, semi di sesamo, cocco',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Pasta di semi di loto',
		'description' => 'Impasto per dessert',
		'ingredients' => 'fiore di loto, zucchero, semi essiccati, olio vegetale',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Tang hulu',
		'description' => 'Frutta ricoperta di caramello',
		'ingredients' => 'frutta candita, zucchero',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Durian fritto',
		'description' => 'frutto impanato e fritto',
		'ingredients' => 'durian, olio, farina',
		'visibility' => true,
		'thumb' => '',
	],
	//japanase 1
	[
		'name' => 'Onigiri',
		'description' => "Riso pressato ripieno di salmone e avvolto da un'alga",
		'ingredients' => 'riso, alga, salmone',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1615361200098-9e630ec29b4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
	],[
		'name' => 'Ramen',
		'description' => 'Spaghetti tipici giapponesi',
		'ingredients' => 'spaghetti di riso, uova, sesamo, miso, zenzero, lonza di maiale, cipollotto',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
	],[
		'name' => 'Tempura',
		'description' => 'Gamberi impanati e fritti',
		'ingredients' => 'gamberi, farina',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Nigiri',
		'description' => 'Riso ricoperto con pesce crurdo',
		'ingredients' => 'riso, salmone, branzino',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=627&q=80',
	],[
		'name' => 'Shabu Shabu',
		'description' => 'Variante giapponese di un piatto cinese',
		'ingredients' => 'fette di carne, verdure, funghi, tofu',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Uramaki',
		'description' => 'Roll di riso ripieni',
		'ingredients' => 'riso, pesce, alga, semi di girasole',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1188&q=80',
	],[
		'name' => 'Soba',
		'description' => 'Spaghetti di grano saraceno tipici giapponesi',
		'ingredients' => 'farina di grano saraceno, brodo di carne, salsa di soia',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Sashimi',
		'description' => 'Fettine di pesce crudo misto',
		'ingredients' => 'pesce crudo',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1562802378-063ec186a863?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Zuppa di miso',
		'description' => 'Zuppa giapponese con fagioli di miso',
		'ingredients' => 'brodo, fagioli di miso, tofu, cipolle verdi',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Tako Yaki',
		'description' => 'Polpette di polpo fritte',
		'ingredients' => 'polpo, zenzero, cipolle, salsa per Tako Yaki, maionese, fiocchi di tempura',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],
	//japanese 2
	[
		'name' => 'Temaki',
		'description' => "Riso e pesce avvolti in un'alga nori a forma conica",
		'ingredients' => 'riso, pesce, alga, uova',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Okonomiyaki',
		'description' => 'Piatto agrodolce giapponese',
		'ingredients' => 'cavolfiore, farina, cipollotto, uova, gamberi, calamari',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1629579436553-6b34e5ddd9de?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Ghioza',
		'description' => 'Fagottini cotti al vapore ripieni di carne',
		'ingredients' => 'farina, carne di maiale, cicoria, cipollotto fresco, salsa di soia, olio di semi',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1924&q=80',
	],[
		'name' => 'Yaki udon',
		'description' => 'Spaghetti udon saltati con salsa di soia, carne e verdure',
		'ingredients' => 'farina di riso, salsa di soia, zenzero, verdure',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1558985212-324add95595a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Katsudon',
		'description' => 'Cotoletta di maiale fritta',
		'ingredients' => 'carne di maiale, panko, salsa di soia, salsa mirin',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Yosenab',
		'description' => 'Misto di carne e verdure',
		'ingredients' => 'salsa di soia, verdure, carne mista',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Bistecca di Kobe',
		'description' => 'Bistecca di pregiatissima carne di Kobe',
		'ingredients' => 'carne di Kobe',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1513135237078-98427911d825?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80',
	],[
		'name' => 'Doraiaki',
		'description' => 'Pankacke ripieni di crema',
		'ingredients' => 'pancake, crema',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Dango',
		'description' => 'Gnocco giapponese',
		'ingredients' => 'riso glutinoso, soia tostata, sciroppo di amido, fagioli rossi, uova, thè verde',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1641887912170-059b45a22a6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1336&q=80',
	],[
		'name' => 'Tayaki',
		'description' => 'Dolce giapponese a forma di pesce',
		'ingredients' => 'marmellata di fagioli rossi, farina',
		'visibility' => true,
		'thumb' => '',
	],
	//indian 1
	[
		'name' => 'Samosa',
		'description' => 'Fagottini ripieni',
		'ingredients' => 'patate, carne, piselli',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1622715395486-08183374570a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Thali',
		'description' => 'Pane indiano servito con salse di vario genere',
		'ingredients' => 'pane, salse',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80',
	],[
		'name' => 'Paratha',
		'description' => 'Pane fritto',
		'ingredients' => 'pane, spezie, patate, salse',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1921&q=80',
	],[
		'name' => 'Panipuri',
		'description' => 'Snack indiano con pane fritto',
		'ingredients' => 'pane, chutney, riso soffiato, melograno',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Kulfi',
		'description' => 'Gelato indiano',
		'ingredients' => 'zafferano, rose, mango',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Pollo al burro',
		'description' => 'Pollo condito con burro e pomodori',
		'ingredients' => 'pollo, burro, pomodori speziati',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1574484284002-952d92456975?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],
	//indian 2
	[
		'name' => 'Lassi',
		'description' => 'Bevanda tipica indiana',
		'ingredients' => 'yogurt, mango, zafferano, banana',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Bhelpuri',
		'description' => 'Spuntino salato con riso soffiato, verdure e spezie',
		'ingredients' => 'chicchi di riso, arachidi, verdure, spezie, melograno',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1593560704563-f176a2eb61db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGluZGlhbiUyMGZvb2R8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60',
	],[
		'name' => 'Pollo al curry',
		'description' => 'Pollo con spezia tipica indiana',
		'ingredients' => 'pollo, curry, yogurt, lenticchie',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1604152135912-04a022e23696?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Polpette al curry',
		'description' => 'Polpette con spezia tipica indiana',
		'ingredients' => 'carne mista, yogurt, noce moscata, latte, pane, curry',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Masala dosa',
		'description' => 'Impasto arrotolato ripieno di patate riso e cipolle',
		'ingredients' => 'farina di riso, curry, patate, riso, cipolle',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8aW5kaWFuJTIwZm9vZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60',
	],[
		'name' => 'Chaas',
		'description' => 'Bevanda a base di dhai',
		'ingredients' => 'yogurt, sale, acqua, spezie miste',
		'visibility' => true,
		'thumb' => '',
	],
	//indian 3
	[
		'name' => 'Chole bhature',
		'description' => 'Mistura di ceci e spezie accompagnate da del pane fritto',
		'ingredients' => 'pane fritto, spezie, ceci',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1581600140682-d4e68c8cde32?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80',
	],[
		'name' => 'Daal',
		'description' => 'Zuppa di lenticchie e spezie',
		'ingredients' => 'lenticchie, spicchi di aglio, olio di arachidi, peperoncini, zenzero',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1596797038530-2c107229654b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
	],[
		'name' => 'Riso biryani',
		'description' => 'Riso tipico indiano con verdure e spezie',
		'ingredients' => 'riso, cavolfiore, peperone, cavolo, cipolla, curcuma, anacardi',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Barfi al cocco',
		'description' => 'Dolci al cocco',
		'ingredients' => 'latte, zucchero, burro, aromi',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Laddoo',
		'description' => 'Dolcetti di forma sferica',
		'ingredients' => 'farina di ceci, zucchero, mandorle, anacardi',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Chutney di mango',
		'description' => 'Salsa di mango e spezie',
		'ingredients' => 'mango verde, aglio, sale, zucchero, polvere di peperoncino',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1573729065599-a8d4bd3bad96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1933&q=80',
	],
	//international 1
	[
		'name' => 'Panino con hamburger',
		'description' => 'Tipico panino americano',
		'ingredients' => 'pane, carne di manzo, pomodori, insalata, cheddar, bacon, cipolle fritte',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Crepes alla nutella',
		'description' => 'Dolce tipico francese ',
		'ingredients' => 'farina, latte, uova, nutella, pecorino romano',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1603701972178-96760b471be9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1364&q=80',
	],[
		'name' => 'Pizza Margherita',
		'description' => 'Pizza cotta in forno a legna',
		'ingredients' => 'farina, olio Evo, pomodoro, mozzarella, basilico',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1589187151053-5ec8818e661b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Cheesecacke',
		'description' => 'Dolce internazionale realizzato con formaggio fresco e marmellata',
		'ingredients' => 'formaggio fresco, panna, burro, marmellata, biscotti',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Fish and chips',
		'description' => 'Piatto tipico inglese con pesce e patatine fritte',
		'ingredients' => 'pesce fritto, patatine fritte',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1576777647209-e8733d7b851d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Zuppa di cipolle',
		'description' => 'Zuppa tipica francese',
		'ingredients' => 'cipolle, burro, farina, brodo, formaggio',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1610725663727-08695a1ac3ff?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1364&q=80',
	],[
		'name' => 'Escargot',
		'description' => 'Piatto tipico francese a base di lumache',
		'ingredients' => 'lumache, burro, prezzemolo, aglio, cipolle',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1614081051719-741fa213aa9c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Paella',
		'description' => 'Piatto tipico spagnolo a base di riso e pesce',
		'ingredients' => 'riso, pesce misto, cipolle, zafferano, paprika, pomodoro',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1630175860333-5131bda75071?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Tortilla di patate',
		'description' => 'Frittata di patate tipica spagnola',
		'ingredients' => 'patate uova, cipolle, sale, olio',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Tacos',
		'description' => 'Tortillas piegate e ripiene di carne, tipiche del Messico ',
		'ingredients' => 'farina di mais, olio di semi, carne macinata, porro, pomodorini, formaggio',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1593759608136-45eb2ad9507d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2059&q=80',
	],
	//international2
	[
		'name' => 'Insalata greca',
		'description' => 'Insalata vegetariana tipica della Grecia',
		'ingredients' => 'feta, olive nere, cetrioli, origano, pomodori',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2080&q=80',
	],[
		'name' => 'Zuppa di gamberi tailandese',
		'description' => 'Piatto tipico tailandese',
		'ingredients' => 'latte di cocco, brodo vegetale, gamberi, erba cipollina, curry, salsa di pesce',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1945&q=80',
	],[
		'name' => 'Porridge',
		'description' => "Pietanza tipica inglese con fiocchi d'avena latte e frutta",
		'ingredients' => "fiocchi d'avena, latte, sciroppo d'acero, vaniglia, frutti di bosco",
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1515544645059-de313dd20a58?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1285&q=80',
	],[
		'name' => 'Insalata di patate tedesca',
		'description' => 'Insalata tipica tedesca',
		'ingredients' => 'patate, cipolla rossa, erba cipollina, brodo, aceto, senape',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Pretzel',
		'description' => 'Biscotto tipico tedesco',
		'ingredients' => 'farina, acqua, zucchero, burro, sale grosso',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1511951786553-1d4f975424c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Gulash',
		'description' => 'Piatto ungherese di spezzatino e spezie',
		'ingredients' => 'manzo, patate, peperoni verdi, cipolle, brodo di carne, paprika, pomodori',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Pastrami',
		'description' => 'Fette di carne di manzo tipico della Romania',
		'ingredients' => 'manzo, semi di coriandolo, chiodi di garofano, paprika dolce, cannella, semi di senape',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Tortillas',
		'description' => 'Pane basso non lievitato tipico del Messico',
		'ingredients' => 'farina di mais, sale, acqua',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Coniglio in umido',
		'description' => 'Piatto tipico francese a base di carne di coniglio',
		'ingredients' => 'coniglio, vino rosso, pancetta, funghi, spezie, patate, burro',
		'visibility' => false,
		'thumb' => '',
	],[
		'name' => 'Quesadillas',
		'description' => 'Antipasto messicano con tortillas, formaggi e pomodori',
		'ingredients' => 'farina di mais, formaggio, mais, pomodoro, erba cipollina, olio',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1606350383072-4b031d6bd834?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],
	//international 3
	[
		'name' => "Spaghetti all'Amatriciana",
		'description' => 'Piatto tipico Italiano della città di Amatrice',
		'ingredients' => 'pomodori, guanciale, peperoncino fresco, olio Evo, pecorino romano',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Bbq ribs',
		'description' => 'Piatto Americano a base di costolette di maiale',
		'ingredients' => 'costolertte di maiale, senape, aglio in polvere, paprika dolce, peperoncino, pepe, sale',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
	],[
		'name' => 'Krapfen alla crema',
		'description' => 'Dolce soffice ripieno di crema pasticciera di origine tedesca',
		'ingredients' => 'farina, latte, uova, zucchero, burro, limone, vaniglia',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1578257264874-5a9858af7d68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1286&q=80',
	],[
		'name' => 'Torta Sacher',
		'description' => 'Dolce austriaco al cioccolato e marmellata di albicocca',
		'ingredients' => 'farina, zucchero, burro, cioccolato, marmellata di albicocche, latte',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1572468890574-26614eaa1401?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
	],[
		'name' => 'French Toast',
		'description' => 'Pane inzuppato nelle uova e fritto, di origine francese',
		'ingredients' => 'pane, uova, latte, cannella, burro, confettura di mirtilli',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1547755986-37898ce06c5b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => "Anatra all'arancia francese",
		'description' => 'Anatra francese preparata con arance fresche',
		'ingredients' => 'anatra, arancia, cipolla, burro, brodo di carne, carote, rosmarino, zucchero',
		'visibility' => true,
		'thumb' => '',
	],[
		'name' => 'Cupcake',
		'description' => 'Dolce americano con crema',
		'ingredients' => 'burro, zucchero, farina, uova, vaniglia, latte, zucchero a velo',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
	],[
		'name' => 'Cipolle fritte',
		'description' => 'Anelli di cipolla fritti molto diffusi in America',
		'ingredients' => 'cipolle, farina, sale, uova, pepe',
		'visibility' => false,
		'thumb' => 'https://images.unsplash.com/photo-1625938146369-adc83368bda7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1925&q=80',
	],[
		'name' => 'kebab',
		'description' => 'Piadina ripiena di carne di pollo, originario del Medio Oriente',
		'ingredients' => 'carne di pollo, tacchino, aromi, paprika, cipolla, insalata, salsa allo yogurt',
		'visibility' => true,
		'thumb' => 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
	],[
		'name' => 'Gnocchi di riso cinesi',
		'description' => 'Gnocchi Cinesi ',
		'ingredients' => 'farina di riso, carote, cipollotto, zenzero, olio di semi, salsa di soia',
		'visibility' => true,
		'thumb' => '',
	],
];